Stage 2 first commit
molestov/java-explore-with-me pull request #4
Opened 2023-07-30 12:31 UTC by molestov

2023-07-31 16:35 UTC, kalitva requested changes

2023-07-31 16:35 UTC, kalitva commented on main-service/Dockerfile
> +COPY target/*.jar main-service.jar
Укажи имя копируемого джарника вместо звездочки

2023-07-31 16:35 UTC, kalitva commented on main-service/src/main/java/ru/practicum/main_service/category/service/CategoryService.java
> +import static ru.practicum.main_service.SystemDefaults.NOT_FOUND_MESSAGE;
На мой взгляд лучше избегать статических импортов (исключение - тестовые классы)

2023-07-31 16:35 UTC, kalitva commented on main-service/src/main/java/ru/practicum/main_service/event/dto/LocationDto.java
> +        if (this == o) return true;
Пожалуйста, фигурные скобки, я знаю, что так intellij генерит, настрой ее правильно

https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used

2023-07-31 16:35 UTC, kalitva commented on pom.xml
> +	</modules>
4 пробела вместо табов

2023-07-31 16:47 UTC, molestov commented on main-service/src/main/java/ru/practicum/main_service/SystemDefaults.java
> +    public static final String DTF_PATTERN = "yyyy-MM-dd HH:mm:ss";
done

2023-07-31 17:07 UTC, molestov commented on main-service/src/main/java/ru/practicum/main_service/compilation/dto/CompilationDtoDefaults.java
> +    public static final int MAX_LENGTH_TITLE = 50;
done

2023-07-31 17:11 UTC, molestov commented on main-service/src/main/java/ru/practicum/main_service/compilation/controller/CompilationPublicController.java
> +            @RequestParam(required = false, defaultValue = SystemDefaults.PAGE_FROM) @PositiveOrZero Integer from,
done

2023-07-31 17:15 UTC, molestov commented on main-service/src/main/java/ru/practicum/main_service/event/dto/LocationDto.java
> +        if (this == o) return true;
done

2023-07-31 17:17 UTC, molestov commented on main-service/src/main/java/ru/practicum/main_service/exception/ErrorHandler.java
> +        log.error(exception.toString());
done

2023-07-31 17:18 UTC, molestov commented on main-service/src/main/java/ru/practicum/main_service/user/service/UserService.java
> +        } else {
done

2023-07-31 17:25 UTC, molestov commented on main-service/src/main/java/ru/practicum/main_service/user/service/UserService.java
> +        userRepository.findById(id)
done

2023-07-31 17:36 UTC, molestov commented on pom.xml
> +	</modules>
done

2023-07-31 17:41 UTC, molestov commented on main-service/src/main/java/ru/practicum/main_service/compilation/controller/CompilationAdminController.java
> +import ru.practicum.main_service.compilation.service.CompilationService;
done

2023-07-31 17:41 UTC, molestov commented on main-service/src/main/java/ru/practicum/main_service/category/service/CategoryService.java
> +import static ru.practicum.main_service.SystemDefaults.NOT_FOUND_MESSAGE;
done

2023-08-01 15:34 UTC, kalitva approved these changes

2023-08-01 15:34 UTC, kalitva commented on main-service/src/main/java/ru/practicum/mainservice/compilation/controller/CompilationAdminController.java
> +    @PatchMapping("/{compId}")
Лучше обойтись без сокращений `compId --> compilationId` Или можно просто - `id`

2023-08-01 15:34 UTC, kalitva commented on main-service/src/main/java/ru/practicum/mainservice/event/service/EventService.java
> +    public List<EventFullDto> getEventsByAdmin(List<Long> users, List<EventState> states, List<Long> categories,
Многовато параметров для метода. Оптимальное число - 1 или 2, 3 - уже много, но допустимо, больше - плохо. Попробуй решить эту проблему, например, используя паттерн Paramater Object 
https://www.baeldung.com/java-best-practices-many-parameters-method

Это касается всех методов за исключением методов контроллеров

2023-08-01 15:34 UTC, kalitva commented on main-service/src/main/java/ru/practicum/mainservice/exception/ErrorHandler.java
> +        log.error(exception.toString());
Залогировать исключение? Нам нужно чтобы в логи попал стэктрейс - 
https://stackoverflow.com/questions/3988788/what-is-a-stack-trace-and-how-can-i-use-it-to-debug-my-application-errors

`log.error(message, exception)`

2023-08-01 18:28 UTC, merged